### ISSUE TITLE
How does the model perform on CULane datasets? 

### ISSUE THREAD

**Issue by SoulmateB** [liuruijin17/LSTR#10]
Thanks, Great and meaningful work！I have got a good result on Tusimple dataset. Have you trained model on CULane datasets？How does it performs on CULane datasets？I am glad to provide a little help as much as I can.

**Comment by liuruijin17** [comment]
Thanks!
I have trained a model on the CULane dataset recently, with the same configuration (no additional parameters) the model achieves 65.6 F1-measure. After multiplying all channels by 2, the F1-measure reaches 68.6.

However, I think my evaluation code might have some problems because the original CULane evaluation protocol considers the segmentation to be the input. I directly generate predicted sequences using my own python codes by depending on their Matlab codes as I understand it (which might have some problems). 

I will update my codes about CULane in the future, but anyway please feel free to pull requests!

**Comment by lunachy** [comment]
> Thanks!
> I have trained a model on the CULane dataset recently, with the same configuration (no additional parameters) the model achieves 65.6 F1-measure. After multiplying all channels by 2, the F1-measure reaches 68.6.
> 
> However, I think my evaluation code might have some problems because the original CULane evaluation protocol considers the segmentation to be the input. I directly generate predicted sequences using my own python codes by depending on their Matlab codes as I understand it (which might have some problems).
> 
> I will update my codes about CULane in the future, but anyway please feel free to pull requests!

any plan about pushing CULane dataset‘s work?

**Comment by liuruijin17** [comment]
In next week. @lunachy

**Comment by liuruijin17** [comment]
I have upload training testing and evaluating codes about culane in the [culane branch](https://github.com/liuruijin17/LSTR/tree/culane), please check it!
Now, I will close this issue.
