### ISSUE TITLE
what's the masks mean?

### ISSUE THREAD

**Issue by cvchanghao** [liuruijin17/LSTR#12]
Thank you for sharing your code !
I am confused 
`masks  = xs[1]  # B 1 360 640`
Why need mask as input ? I can't find it in the paper

**Comment by liuruijin17** [comment]
Hi, sorry for answering so late.
The mask is used to indicate which pixels are useful appearances and which are padded zeros since every image is augmented before fed into the network.

You can use cv2 to visualize the mask and its corresponding augmented image, then you can get the idea.

Besides, the mask is used to generate positional embedding and indicate that the locations which are padded zeros are not used to extract non-local dependencies in the Transformer module.

**Comment by cvchanghao** [comment]
Got it, Thank you !
