### ISSUE TITLE
tusimple model predict on another dataset seems weired

### ISSUE THREAD

**Issue by jinfagang** [liuruijin17/LSTR#18]
tusimple model predict on another dataset seems weired

![image](https://user-images.githubusercontent.com/21303438/101466388-0ce51600-397c-11eb-8927-4682f9eda314.png)

what missed here?

**Comment by jinfagang** [comment]
@liuruijin17 I think it maybe some coordinates issue? For semantic prediction, it at least knows where is the lane on the ground, rather than up to the sky,

**Comment by jinfagang** [comment]
@liuruijin17 Can u post a your self-collected image prediction effect using cached model?

**Comment by liuruijin17** [comment]
Hi,

In fairness to the discussion about lane locating performance, I wish we had only discussed the TuSimple dataset. Because any model will probably not perform well on data that has never been seen before, which is the downside of a data-driven approach to deep learning.

The segmentation task focuses on recognizing each pixel, and a segmentation model trained on TuSimple might know the lane pixel on other datasets because there is no overall concept of lanes here, just lane pixels. However, our approach directly treats the lane as an overall object, so the current situation across different datasets is perfectly normal.

**Now I share two self-collected images, you can directly test the results by the provided TuSimple trained model, and you will see one is better than the other.**

We also have data on intersections, etc., but there is no point in testing it here since our approach cares about the high-level lane objects, not low-level lane pixels.
![180707000_123357AA_1500](https://user-images.githubusercontent.com/29913368/101480546-c947d780-398e-11eb-8eff-b83f5a217e78.jpg)
![180707000_123357AA_1800](https://user-images.githubusercontent.com/29913368/101480554-ce0c8b80-398e-11eb-80d8-d7d77eb543d5.jpg)

**Comment by jinfagang** [comment]
@liuruijin17  thank u! I will test tomorrow. My point is not Tusimple trained model also works on other dataset, it's it at least fit the lane shape in some sort of style instead. I have tested UltraFastLane detection model trained on CULane, it also have floating to the sky issue, but in the end I found it's a coordinates converting issue since my image WH not same as CULane's.

**Comment by liuruijin17** [comment]
Hi, sorry for being late, tough days because my cat got sick.

I think I understand your point. I tried to crop your image to 511x1421 then test with the CULane pre-trained LSTR since our input is 295x820, the result is still bad. So I wonder whether the cropping processing I did is like yours (just semantically rather than in terms of specific values).  

Another thing I realized that our model prefers traditional object detection, so the overall apparent clues of the lane markings are critical. For scenarios where lane markers are missing, LSTR may not predict well (test results on CULane shows that point).

The last thing is I think UltraFastLane learns from the segmentation information and focuses more on low-level features so that it is more robust on different scenes than LSTR which learns a lane as a whole object. So the trade-off is that LSTR needs more data to see and conquer, which I think there is still a cap anyway:joy_cat:. The ultimate solution may still have to rely on the fine-grained split of scenarios and tasks.

**Comment by jinfagang** [comment]
@liuruijin17 thanks for your investigation! Indeed, more data is likely the way how transformer based model performance even better.

I also tested with different resize way or cropping, no luck. 

However LSTR still a promising model since it learn better on curved scenarios. BTW will u planned to come up with a second version of LSTR in the future which might add a semantic branch or something fancy way to tweaking it?

**Comment by liuruijin17** [comment]
@jinfagang you are welcome! It's nice to make a little something useful.

Yes, recently I have been reading papers about 3D lane detection, like [3DLaneNet](https://openaccess.thecvf.com/content_ICCV_2019/papers/Garnett_3D-LaneNet_End-to-End_3D_Multiple_Lane_Detection_ICCV_2019_paper.pdf) and [Gen-LaneNet](https://arxiv.org/abs/2003.10656), to seek some ideas about how to expand the detection results of different camera poses, maybe use the hot domain adaptation topic. However, I find the dataset is the main bottleneck since the public 2D or 3D lane datasets are too general to focus on fine-grained scenarios like intersections, merges and splits, and lack annotations to specify them. Perhaps we will start with the dataset to define some novel problems, which may also solve the original issues at the same time.

**Comment by jinfagang** [comment]
@liuruijin17  Waiting for your progress!
