### ISSUE TITLE
Questions about LSTR's performance.

### ISSUE THREAD

**Issue by lunachy** [liuruijin17/LSTR#19]
I just tested the performance，and the result seems not that fast，just about 100fps. Is there something wrong with the testing method？Here's the testing code below.

<details>
<summary>speed_simple</summary>

```python
import torch
import time
import numpy as np
from nnet.py_factory import NetworkFactory
from config import system_configs
import os
import json

cfg_file = os.path.join(system_configs.config_dir, "LSTR.json")
print("cfg_file: {}".format(cfg_file))
with open(cfg_file, "r") as f:
    configs = json.load(f)

configs["system"]["snapshot_name"] = "LSTR"
system_configs.update_config(configs["system"])

torch.cuda.set_device(0)
torch.backends.cudnn.benchmark = True
nnet = NetworkFactory()
nnet.load_params(500000)
nnet.cuda()
nnet.eval_mode()

input_size = [360, 640]
images = torch.zeros((1, 3, input_size[0], input_size[1]), dtype=torch.float32).cuda() + 1
masks = torch.ones((1, 1, input_size[0], input_size[1]), dtype=torch.float32).cuda() + 2

for i in range(10):
    outputs, weights = nnet.test([images, masks])

t_all = []
for i in range(200):
    torch.cuda.synchronize(0)
    t1 = time.time()
    outputs, weights = nnet.test([images, masks])
    torch.cuda.synchronize(0)
    t2 = time.time()
    t_all.append(t2 - t1)

print('average time:', np.mean(t_all) / 1)
print('average fps:', 1 / np.mean(t_all))

print('fastest time:', min(t_all) / 1)
print('fastest fps:', 1 / min(t_all))

print('slowest time:', max(t_all) / 1)
print('slowest fps:', 1 / max(t_all))

```
</details>

![image](https://user-images.githubusercontent.com/10249962/101606354-454d2880-3a3e-11eb-9175-d7fb3beced33.png)

**Comment by liuruijin17** [comment]
Please read the README.md carefully.

The MACs and the number of parameters are more important than an FPS evaluated on graphics cards. Speed is just a matter of implementation.

If you test the time consumption of each module you will find that the speed is mainly consumed by the Transformer. However, there are many fast implementation versions of the Transformer, like [Faster Transformer](https://github.com/NVIDIA/DeepLearningExamples/tree/master/FasterTransformer), which could speed up LSTR again but  is not our concern currently. 

Besides, for research and algorithm landing purposes, the computation complexity is more compelling than the speed on the graphics card since no matter how fast you run the algorithm on the graphics card, the computational complexity of the algorithm and the number of parameters are independent of the implementation.

**Comment by lunachy** [comment]
I agree with the importance of MACs(0.574G) and  the number of parameters(0.77M) of your model. 
But it can't explain the fast speed(420fps) in the paper. However the speed is the one of core points in your paper.
As you described, you tested TuSimple dataset without bells and whistles.
So I wonder how do you test your model's speed? 

![image](https://user-images.githubusercontent.com/10249962/101615211-d6c19800-3a48-11eb-8aee-e6d3e95f69cb.png)

![image](https://user-images.githubusercontent.com/10249962/101615255-e17c2d00-3a48-11eb-8163-80ebe3d33522.png)

**Comment by liuruijin17** [comment]
:slightly_smiling_face: What you are seeking lies in the README.
![emm](https://user-images.githubusercontent.com/29913368/101618382-e3e08600-3a4c-11eb-84be-389ca4e0d7b1.PNG)

**Comment by lunachy** [comment]
emmm……
According to my opinion, FPS has nothing to do with batch. It's calculated by one inference, one image, one time.
The number of images the model can predicts every time just depends on the video memory.
You can read the speed testing code below for reference.
https://github.com/cfzd/Ultra-Fast-Lane-Detection/blob/master/speed_simple.py

**Comment by liuruijin17** [comment]
FPS has nothing to do with batch? WOW!

Video memory? So you think a video application MUST process video frames one by one? WOW!

The UltraFast measures one frame speed only because their memory cost is very large.
Processing **1** 3x288x800 image uses **1190MiB** GPU memory usage, but processing **16** 3x360x640 images only use **877MiB** by our method.
Also, the number of parameters is 71, 333, 800, but ours is only 765, 787.

**More importantly, why do not you test the batch performance of UltraFast?**

**Comment by liuruijin17** [comment]
Now on my platform, using the python script you linked, iterations=1000, when batch=1, UltraFast runs 202 fps and uses1189MiB GPU memory usage; when batch=16, UltraFast runs 299 FPS and uses 5653MiB GPU memory usage.  You can list the performance of LSTR evaluated by you own and you will get the idea.

**Comment by lunachy** [comment]
Model serving is another thing. It depends on the real scenario.
It may process one frame one time in real time scenario, or process batch frames one time in non-real time scenario.
According your opinion,  FPS has relationship with batch, more batch corresponds to higher FPS theoretically, so how to define FPS.
If the GPU memory is unlimited, FPS is infinitely great?
DL papers about fps has never mentioned corresponding batch parameter.
And I run the python script directly, here's the result below.
![image](https://user-images.githubusercontent.com/10249962/101634773-1d70bb80-3a64-11eb-9d28-776db68e90a8.png)

**Comment by liuruijin17** [comment]
How a GPU memory can be unlimited? What’s your point? I never want the gpu memory to be unlimited. 

I list the FPS performance and the memory usage, why you always ignore the cost of gpu memory of different methods when discussing?

You run the code, don’t you see their FPS performance gains a little and is slower than LSTR? Do you ever just think a little why this happens?

What a joke that “DL papers about FPS has NEVER mentioned corresponding batch parameters”. 

DL papers care about computation complexity, and FPS is just a matter of implementation. If you do not accept that idea, please do not disturb me and I will keep this issue open.

**Comment by lunachy** [comment]
I said I agree with the importance of MACs(0.574G) and the number of parameters(0.77M) of your model.
I also care about computation complexity.
And we argue about if FPS has relationship to do with batch. The FPS here is just standard criterion, not the practical model serving result or implementation result.
If it does, how do you get your 420fps? batch=16? It seems unfair to compare with others whose batch=1. Or at least you should mark out batch=16 in your paper.
If it does not, well you seems disagree with this.

**Comment by liuruijin17** [comment]
**You said, "The FPS here is just standard criterion, not the practical model serving result or implementation result",  but did you know the convolution operation has been accelerated very fast through years of effort by many accelerating methods _(you need CUDA to run any PyTorch codes, don't you ever think why?)_, but the PyTorch implementation of Transformer seems to have no such treatment. I have repeatedly asked you to focus on computation complexity because it is the ONLY criterion that has nothing to do with implementation, not the FPS you think ideally (standard criterion??? how standard??? which criterion??? are you living in your own world???).**

How to measure speed has been written on the README **since the beginning of this repo**.

I don't know who you are but I still respect your passion, so could you please:
1. think that why other methods do not increase FPS significantly after increasing parallel data throughput by 16 times;
2. find a method that achieves ~96.18 TuSimple accuracy and runs faster than LSTR in any case on any of your own platform.

Then I will be willing to discuss with you. Otherwise, please do not waste our time and public resources. 

By the way, the other issue you raise also makes me confused #20. Normally I would help anyone who raises issues, but I've never been able to get your point. I think you just live in your own world.

**Comment by lunachy** [comment]
I don't want to discuss with you any more. Maybe it's you who lives in his own world.
Lightweight model doesn't mean fewer cost time. 
Lane detection belongs to driverless field! Do you think how to apply this? predict batch after driving a long time or predict one by one in real time? No matter how high fps can get, it's meaningless if the cost time can't be low.
Maybe you just research for research's sake, regardless of the actual application scenario. Real time is its premise!
If using batch prediction, fps can be higher more or less, why other models don't calculate fps in this way? Maybe you should think about it carefully.
With all the power of irony, how horrible and arrogant!
Well, you are right about everything, do not waste our time and public resources, just close it!

**Comment by liuruijin17** [comment]
Our company has applied a faster version Transformer to accelerate LSTR (weak up! you are just a rookie), which achieves an incredible speed FPS number you'd never imagine on a real mobile chip. 

If you are very happy to use BIG models to detect lanes on GPU in 300 FPS, WOW, you are so clever and the smartest genius in the world. Yes, you are the best and the most polite questioner. **I am horrible and arrogant!!!:smiling_imp::smiling_imp::smiling_imp:** So what? You are just an anonymous pathetic clown hiding in the corner of the internet. However, it's good that you're having fun on your own.

**Comment by lunachy** [comment]
Well, it seems modesty and politeness being laughted and rudeness being advocated, you put the cart before a horse! The moral degeneration of the world is getting worse day by day.
If you think my question is low, you can just ignore it or close it. **Mock、sarcasm、persiflage and personal attack**, is it necessary? The spirit of keyboard man is in full play on you. Can't even imagine it's a PHD's words.
You are all right about everything, OK? **Don't comment any more.** When did it get so hard to be polite?

**Comment by liuruijin17** [comment]
Please look at how other guys raise issues and how I answer them. Out of enthusiasm,  I discuss issues with every person.

However, when did Ph.D. status become a kind of moral kidnapping?
**No matter what my status is, I am only targeting you for mock, sarcasm, persiflage, and personal attack.** :smiling_imp:

**Comment by lunachy** [comment]
Not moral kidnapping, but the basic morality of being a man. Like don't swear first, don't hit first. 
 Don't your teacher tell you how to be a man, or just tell you how to do research? 
Maybe you are right, education has nothing to do with morality.
As I said, If you think my question is low, you can just ignore it or close it. Sarcasm may not be the appropriate way.
When one person disagrees with you or can't understand you, mock, sarcasm, persiflage, and personal attack are your first action? You are so mean? When did it get so hard to seek common points while reserving difference.
Well, as you said, it's good that you're having fun on your own. Looking at you screaming、laughing, it's like watching a clown jump, please stop your poor histrionics, so **ridiculous and lugubrious**.

**Comment by liuruijin17** [comment]
I never feel that there is a high or low level of questions, however, from all other issues that you raised  #20 and [talengu/Wox.Plugin.BookmarkSearcher/issues/9](https://github.com/talengu/Wox.Plugin.BookmarkSearcher/issues/9) (other authors do not even want to talk to you), I think you should mind your manners first.

Again, please look at how other guys raise issues and how I answer them.

Just say "less morality, mean, mock, sarcasm, persiflage, personal attack, ridiculous and lugubrious" or any words you used to attack me. I think your self-presentation is very appropriate.

**Comment by lunachy** [comment]
So polite man should always blindly self-surrender? Can't he fight back?
It's you who reacts in these manners first(mock、sarcasm、persiflage and personal attack), and you **admin** it in the reply!(No matter what my status is, I am only targeting you for mock, sarcasm, persiflage, and personal attack.)
One question I asked don't be answered, such a small thing deserves talking? Maybe the pictures don't upload successfully.
How mean you are! You are so boring to browse my record? So you can find mudslinging to humiliate me? Do you have psychological shadows?
And as you say, other authors don't answer me, it's OK for me and everything's fine. Can't you learn it?

**Comment by liuruijin17** [comment]
I just repeat the words you say to me, if you think that was an admin (admit I guess), sorry I overestimated your emotional and intellectual quotient.

When did **GitHub's contribution activity** is kind of **personal privacy**?  

So I just click your GitHub profile then you think I have psychological shadows? 

Hey, calm down, will you?

**Comment by lunachy** [comment]
‘I am only targeting you for mock, sarcasm, persiflage, and personal attack‘
How clear it is？And **you can't even admit your words**! Being a man, can you be of some responsibility?
As I repeated, no matter how low the question or how stupid you look at me, just ignore it, close the issue or even delete the issue. Is there any reason you attack me first?
Maybe you have strong research ability, but the morality, emmm, you don't derserve it!

**Comment by nigyiii** [comment]
我佛了

**Comment by voldemortX** [comment]
Just can't help myself to say something after spotting this issue. Not to take anyone's side, I believe it is only proper to add a disclaimer in the arxiv version to support the batching choice, by saying the model is actually too small to show superiority on Teraflops GPUs due to a low utility rate (or possibly I/O constrains). **Although we all admit LSTR is ultra fast and probably still the fastest, batching it in the FPS test does not appear to be common practice and should've been stated on the record for future reference.**

p.s. I wonder if it is possible for LSTR to achieve real-time on CPU/Jetson. Listing CPU inference speed for fast algorithms is also good choice to show great performance.

**Comment by liuruijin17** [comment]
Hi, thanks for you understanding.
I will update the arxiv to clarify batch=1's FPS and batch=16's FPS on the Table.

**Comment by voldemortX** [comment]
@liuruijin17 That's great to hear! Recently I've been thinking that maybe instead of changing batch-size, changing the input resolution is a more logical choice to profiling different methods. We might get round to that later [here](https://github.com/voldemortX/pytorch-auto-drive/issues/4).

**Comment by Chenfy13** [comment]
> I just tested the performance，and the result seems not that fast，just about 100fps. Is there something wrong with the testing method？Here's the testing code below.
> 
> speed_simple
> ![image](https://user-images.githubusercontent.com/10249962/101606354-454d2880-3a3e-11eb-9175-d7fb3beced33.png)

Hello, I use your code speed.py , and then the following error appears, sincerely ask what is the reason?

Traceback (most recent call last):
  File "speed.py", line 19, in <module>
    nnet = NetworkFactory()
  File "/home/cfy/TuSimple/LSTR/nnet/py_factory.py", line 67, in __init__
    macs, params, = profile(self.model, inputs=(input_test, input_mask), verbose=False)
  File "/home/cfy/miniconda3/envs/lane/lib/python3.8/site-packages/thop/profile.py", line 188, in profile
    model(*inputs)
  File "/home/cfy/miniconda3/envs/lane/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/cfy/TuSimple/LSTR/nnet/py_factory.py", line 39, in forward
    return self.module(*xs, **kwargs)
  File "/home/cfy/miniconda3/envs/lane/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/cfy/TuSimple/LSTR/models/py_utils/kp.py", line 213, in forward
    return self._test(*xs, **kwargs)
  File "/home/cfy/TuSimple/LSTR/models/py_utils/kp.py", line 208, in _test
    return self._train(*xs, **kwargs)
  File "/home/cfy/TuSimple/LSTR/models/py_utils/kp.py", line 185, in _train
    p = self.conv1(images)  # B 16 180 320
  File "/home/cfy/miniconda3/envs/lane/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/cfy/miniconda3/envs/lane/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 423, in forward
    return self._conv_forward(input, self.weight)
  File "/home/cfy/miniconda3/envs/lane/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 419, in _conv_forward
    return F.conv2d(input, weight, self.bias, self.stride,
RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same

**Comment by Chenfy13** [comment]
> Hi, thanks for you understanding.
> I will update the arxiv to clarify batch=1's FPS and batch=16's FPS on the Table.

hello, have you updated it ?
