### ISSUE TITLE
如何不使用TuSimple数据集呢，也就是使用预训练模型来测试自己的图片

### ISSUE THREAD

**Issue by AI-sudo** [liuruijin17/LSTR#23]
我在准备TuSimple数据集json结构时遇到些问题，而且数据量太大

**Comment by mrc736** [comment]
我也想先测试一下自己的数据，请问你成功了么？

**Comment by liuruijin17** [comment]
Sorry for being late, tough months about lots of deadlines.

I think my codes about testing on other images are not well written, the 'db' object is not necessary when testing on other images, you can replace corresponding constants by directly assigning their values rather than get from the 'db' object attributes.

No training and directly use pre-trained models
1-1 TuSimple
Make sure the aspect ratio of your image is 360 to 640, then our test protocol resizes your input image to 360 x 640.
1-2 CULane
Make sure the aspect ratio of your image is 295 to 820, then our test protocol resizes your input image to 295 x 820.
1-3 Why not good?
Currently, images in TuSimple contain only highway scenes, and the quantity is small. Another CULane contains urban scenes a lot but still suffers the lack of lane shape pattern (curved, closely curved, remotely curved, ...).
1-4 How to improve?
Crop (or any other transformations) your images to make them have similar shape patterns like CULane (or TuSimple) since we treat each lane as a whole object.
