### ISSUE TITLE
Label  own dataset

### ISSUE THREAD

**Issue by foxkw** [liuruijin17/LSTR#25]
Hi, please ask How to  annotate own dataset in the same format as Tusimple? I want to test model  on my own dataset

**Comment by liuruijin17** [comment]
Sorry for being late, tough months about lots of deadlines.

Actually, the question about how to get the same format is hard to give you, maybe you can e-mail the authors of TuSimple to borrow their labeling tools and basic codes. 

Here, I can only give you some tips about how we annotate images.

Annotating your image and training
1-1. How to annotate? (Some recommendations)
1). Annotate each lane with keypoints (10 ~ 20 points is ok, you can sparsely label the close part and densely label remote curved part for better performance on remote curved structures).
2). Make sure the occluded part is correctly imaged when you annotate a lane
3). Make sure the heavily occluded lane is labeled as ignored
4). 2) and 3) are important to form consistent shape guidance, which avoids the problem of marker-appearance misalignment brought about by arbitrary markers.
5) 2), 3) and 4) are found based on the fact that we treat each lane as a whole object (like a cat or dog in the object detection field) rather than low-level pixels.
6) Remember and think 5), you will make your mind about the advantages and disadvantages of LSTR.
