### ISSUE TITLE
A simple question.

### ISSUE THREAD

**Issue by NARRZ** [liuruijin17/LSTR#36]
****I am so sorry but I am a beginner,I want to know how do you achieve **Hungarian Fitting Loss**.Please tell me in detail(eg,in detr_loss, Lines 25 to 47 ), thank you very much.

**Comment by liuruijin17** [comment]
Given an image.
Assuming 3 GT lanes noted as L1, L2, L3.
Assuming LSTR generates 3 predicted curves Pa, Pb, Pc
Hungarian Fitting Loss will operate:
1. Calculate a matching cost matrix:

|                  | L1            |  L2            |    L3         |
| ------------- | ------------- | ------------- | ------------- |
|Pa             |1.1             |  3.2          |   2.5          |           
|Pb             |1.8             |   1.3         |  3.9           |
|Pc             |5.3             |    4.2        | 2.2             |


Then we can get an optimal injective function z(i) where z(1) = a, z(2)=b, z(3)=c


2. Use z(i) to calculate loss
The fitting error for L1 is generated according to Pa since z(1)=a; 
likewise for L2 and L3


In general, the Hungarian fitting loss first associates ground truth with estimation curves, then calculates losses of each ground truth according to its corresponding estimation.

If you still have any questions, I am happy to discuss the pipeline in any detail.
