### ISSUE TITLE
Is the trained parameter model valid only for the same camera?

### ISSUE THREAD

**Issue by zsffuture** [liuruijin17/LSTR#37]
Hello, is your algorithm model only useful for images produced by a fixed camera?If you have multiple cameras with different angles, isn't it possible to use the same set of parameters?Because your algorithm involves calculating the Angle of the camera?

**Comment by liuruijin17** [comment]
Hi, we have tried several datasets which collect images using different camera parameters. Results are good when applying supervising learning on them since we use Eq. 4. 

Eq.4 just thinks every image is generated from a virtual camera which is different from any other images.

If you want to calculate the angle, you can use Eq. 3 and reframe output to the corresponding coefficients
