### ISSUE TITLE
The meaning of lighting augmentation

### ISSUE THREAD

**Issue by voldemortX** [liuruijin17/LSTR#51]
Hi! I'm trying to understand what is the [lighting augmentation](https://github.com/liuruijin17/LSTR/blob/6044f7b2c5892dba7201c273ee632b4962350223/utils/image.py#L12)? Are the [eigen values](https://github.com/liuruijin17/LSTR/blob/6044f7b2c5892dba7201c273ee632b4962350223/db/tusimple.py#L87) representative of a light source & do I need to compute them for other datasets?

Could you help me with this @liuruijin17, thanks very much!

**Comment by liuruijin17** [comment]
The lighting functions come from [CornerNet](https://github.com/princeton-vl/CornerNet). And in their paper, they said "we adopt standard data augmentation including ..., random color jittering. Finally, we apply PCA to the input image." So the lighting augmentation here is to highlight the network the most principal image features.

You could compute them from other datasets, which would be more reasonable since not all datasets share the same intensity distribution.

**Comment by voldemortX** [comment]
Thanks! So the numbers from your repo at the moment are the ones from COCO dataset?

**Comment by liuruijin17** [comment]
You're welcome.

Maybe. There are no comments from CornerNet's authors. 

This question also shows up in CornerNet's repo, such as
issue [163](https://github.com/princeton-vl/CornerNet/issues/163), [85](https://github.com/princeton-vl/CornerNet/issues/85), [75](https://github.com/princeton-vl/CornerNet/issues/75), but no responses.

**Comment by voldemortX** [comment]
@liuruijin17 Yes, I see that. Since https://github.com/princeton-vl/CornerNet/issues/163 is open, I'll close this one and post future inquiries there.
