### ISSUE TITLE
confused for rotate aug (formular 12)

### ISSUE THREAD

**Issue by andongchen** [liuruijin17/LSTR#63]
https://github.com/liuruijin17/LSTR/blob/6044f7b2c5892dba7201c273ee632b4962350223/db/tusimple.py#L71

Sorry ,I  hanve some confused for rotate aug .When rotate, there will have roll angle. But formula 12 in you paper is only consider pitch angle.
![rotate](https://user-images.githubusercontent.com/21114260/140308218-4ec17cec-a377-4618-b6ef-69642345638f.png)

**Comment by liuruijin17** [comment]
Hi, thanks for your interest!

The point is we want the network to implicitly think that each image is photoed with its own virtual camera which only has a pitch angle. 

It's a bit wired, but the 'after' image actually could be photoed by a camera that only has a pitch deviation since the black-0-region is masked. Do not mask them is also ok since the network focuses on lanes, not the roads or sky.

**Comment by andongchen** [comment]
Got it.  
Thank you for your reply！
